/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskClientsRouteImport } from './routes/_desk/clients'
import { Route as DeskPipelineRouteImport } from './routes/_desk/pipeline'
import { Route as DeskTrackersRouteImport } from './routes/_desk/trackers'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskClientsRoute = DeskClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPipelineRoute = DeskPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTrackersRoute = DeskTrackersRouteImport.update({
  id: '/trackers',
  path: '/trackers',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/clients': typeof DeskClientsRoute
  '/pipeline': typeof DeskPipelineRoute
  '/trackers': typeof DeskTrackersRoute
}
export interface FileRoutesByTo {
  '/clients': typeof DeskClientsRoute
  '/pipeline': typeof DeskPipelineRoute
  '/trackers': typeof DeskTrackersRoute
  '/': typeof DeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/_desk/clients': typeof DeskClientsRoute
  '/_desk/pipeline': typeof DeskPipelineRoute
  '/_desk/trackers': typeof DeskTrackersRoute
  '/_desk/': typeof DeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clients' | '/pipeline' | '/trackers'
  fileRoutesByTo: FileRoutesByTo
  to: '/clients' | '/pipeline' | '/trackers' | '/'
  id:
    | '__root__'
    | '/_desk'
    | '/_desk/clients'
    | '/_desk/pipeline'
    | '/_desk/trackers'
    | '/_desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/clients': {
      id: '/_desk/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DeskClientsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/pipeline': {
      id: '/_desk/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof DeskPipelineRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/trackers': {
      id: '/_desk/trackers'
      path: '/trackers'
      fullPath: '/trackers'
      preLoaderRoute: typeof DeskTrackersRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskClientsRoute: typeof DeskClientsRoute
  DeskPipelineRoute: typeof DeskPipelineRoute
  DeskTrackersRoute: typeof DeskTrackersRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskClientsRoute: DeskClientsRoute,
  DeskPipelineRoute: DeskPipelineRoute,
  DeskTrackersRoute: DeskTrackersRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
